name = "Blueprints"
uuid = "0e25da23-48ae-47a7-b185-c5bd5c070cab"
version = "0.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
Carlo = "780c37f4-4e5a-43de-9e79-65c261e525a4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extensions]
BlueprintsCarloExt = "Carlo"
BlueprintsJSONExt = "JSON"

[compat]
Carlo = "0.2.3 - 0.3"
DataStructures = "0.19.1"
JLD2 = "0.6"
JSON = "1"
PrecompileTools = "1.2.1"
Random = "1.10.0"
Test = "1.10.0"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Carlo"]
